#!/usr/bin/env node
/**
 * Builds SKILL.md (repo root) — a single, paste-ready file that merges every skill +
 * the scopes + tool-reference docs into one document, for agents that take a
 * single instruction/context blob instead of a skills directory (openclaw,
 * hermes-agent, etc.).
 *
 * The source skills/docs are the single source of truth; this regenerates the
 * bundle so it never drifts. Run after editing any source:
 *
 *   node scripts/build-skills-bundle.ts
 *
 * No dependencies / no build step — relies on Node's native TypeScript type
 * stripping (Node 22.18+ or 23.6+). CommonJS module (the repo has no
 * package.json, so a plain `.ts` runs as CJS).
 */
const { readFileSync, writeFileSync } = require('node:fs');
const { resolve } = require('node:path');

const ROOT: string = resolve(__dirname, '..');

// Generated output, written at the repo root. Note: this is the consolidated
// "everything" bundle — distinct from the per-skill skills/<name>/SKILL.md files.
const OUTPUT_FILE: string = 'SKILL.md';

// Order matters: foundation first, then domain skills, then reference appendices.
const SOURCES: string[] = [
  'skills/using-sanabot/SKILL.md',
  'skills/sanafi-portfolio/SKILL.md',
  'skills/sanafi-card/SKILL.md',
  'docs/scopes.md',
  'docs/skills-reference.md',
];

/** Remove a leading YAML frontmatter block (`---\n … \n---`) if present. */
function stripFrontmatter(text: string): string {
  if (!text.startsWith('---')) return text;
  const close = text.indexOf('\n---', 3);
  if (close === -1) return text;
  const afterLine = text.indexOf('\n', close + 1);
  return afterLine === -1 ? '' : text.slice(afterLine + 1);
}

/** Demote every ATX heading by one level (`#`→`##`, capped at 6), skipping
 *  fenced code blocks so `#` comments inside ```bash blocks aren't touched. */
function demoteHeadings(text: string): string {
  let inFence = false;
  return text
    .split('\n')
    .map((line: string): string => {
      if (/^\s*(```|~~~)/.test(line)) {
        inFence = !inFence;
        return line;
      }
      if (inFence) return line;
      const m = line.match(/^(#{1,6})(\s)/);
      if (!m) return line;
      const level = Math.min(m[1].length + 1, 6);
      return '#'.repeat(level) + line.slice(m[1].length);
    })
    .join('\n');
}

/** GitHub-style heading slug for TOC anchors. */
function slug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-');
}

type Section = { rel: string; title: string; body: string };

const sections: Section[] = SOURCES.map((rel: string): Section => {
  const raw: string = readFileSync(resolve(ROOT, rel), 'utf8');
  const body: string = demoteHeadings(stripFrontmatter(raw).trim());
  // Section title = the first H2 in the demoted body (the source's former H1).
  const m = body.match(/^##\s+(.+)$/m);
  return { rel, title: m ? m[1].trim() : rel, body };
});

const banner: string =
  '<!-- AUTO-GENERATED by scripts/build-skills-bundle.ts — do not edit by hand. '
  + 'Edit the source skills/docs and re-run the script. -->';

const intro: string = `# Sana Bot — Full Skills & Reference Bundle

> One file with everything an AI agent needs to use [Sana Bot](https://sana.bot) on Solana — connection, scopes, and the full portfolio + card workflows. Built for agents that take a single instruction/context blob instead of a skills directory (e.g. openclaw, hermes-agent).

**How to use:** give this whole file to your agent as its instructions / system context, then connect the Sana Bot MCP server and export your key:

\`\`\`
MCP server : https://mcp.sana.bot/mcp
header     : Authorization: Bearer \${SANABOT_API_KEY}
\`\`\`

\`\`\`bash
export SANABOT_API_KEY=sana_live_...
\`\`\`

Generated from the source skills in [\`sanafi-onchain/sanabot-skills\`](https://github.com/sanafi-onchain/sanabot-skills) — do not edit this file directly.`;

const toc: string = '## Contents\n\n'
  + sections.map((s: Section): string => `- [${s.title}](#${slug(s.title)})`).join('\n');

const out: string = [banner, intro, toc, ...sections.map((s: Section): string => s.body)].join('\n\n---\n\n') + '\n';

writeFileSync(resolve(ROOT, OUTPUT_FILE), out);
console.log(`Wrote ${OUTPUT_FILE} — ${sections.length} sections, ${out.length} bytes`);
